### PR TITLE
 test data for QoRTs

### PR DESCRIPTION
**Pull request by pzumbo**
added test data for QoRTs in re  https://github.com/ewels/MultiQC/issues/564  . 

gene diversity is calculated from gene counts file.  

strand test and mapping stats can be obtained from summary file.

### CODE REVIEW

**Comment by ewels** [comment]
Thanks @pzumbo! I'll have to check that calculating the gene diversity profiles from the counts isn't too computationally expensive - usually my policy is that MultiQC should parse summary stats rather than calculating anything itself (I always have to assume that people will run the code on ten thousand samples and want it to finish quickly). But this should be a fairly easy one to do I think, and it certainly doesn't hurt to have the example data.

Are the gene counts files always gzipped like this? 

Phil

**Comment by ewels** [comment]
@pzumbo - nudge.. Are the gene counts files always gzipped like this? I just want to double check before I start writing gunzipping functions into the code (which I'd much rather avoid)....

**Comment by pzumbo** [comment]
Apology for the delay -- the files come gzipped from QoRTs, yes.

Best,
-Paul

**Comment by ewels** [comment]
Great, thanks! 👍

**Comment by ewels** [comment]
Sorry, second question - how stable are the filenames? They look consistent in the files you've updated here, but the summary table (`QC.summary.txt`) is different to the previous one I had (`summary.table.txt`). Can I search by filename? I guess not...

**Pull request merged**
