### PR TITLE
Add spaceranger test reports

### PR DESCRIPTION
**Pull request by grst**
Testdata for https://github.com/ewels/MultiQC/pull/1945

### CODE REVIEW

**Review by ewels — APPROVED** [review]
Thanks!

**Comment by ewels** [comment]
Wow, this is from _very_ subsampled data 😅 I don't suppose you have any reports kicking around with more realistic values? It would help to sanity check the resulting MultiQC report a bit more..

**Comment by grst** [comment]
This is the test data from the nf-core/spatialtranscriptomics pipeline. The only real data I have is proprietary and I don't think I'm allowed to share the report publicly.

**Comment by ewels** [comment]
Is there any example data on the 10x website? What about full size tests for the pipeline?

**Comment by grst** [comment]
There are some samples on the 10x website, but afaik it's just single unrelated samples, so they would make a boring QC report. 

Full-sized test dataset is an open issue: https://github.com/nf-core/spatialtranscriptomics/issues/48. 
The proper solution would be to find a suitable full-sized test-dataset.

**Comment by ewels** [comment]
Can have multiple HTML reports with one sample though, this would be in addition to what you already have. So I think that might still be worth it?

Can add the full size test results later maybe as well

**Comment by grst** [comment]
See https://github.com/ewels/MultiQC_TestData/pull/260

I was first afraid I'd have to run the pipeline on the raw data, but the HTML reports are directly available from the 10x website.

**Pull request merged**
