### PR TITLE
Stacks test data

### PR DESCRIPTION
**Pull request by remiolsen**
For the much anticipated Stacks module :wink:

### CODE REVIEW

**Comment by ewels** [comment]
giphy

**Comment by remiolsen** [comment]
@ewels. Random thought. Should I perhaps name this module `stacks2`? Theres maybe only 1/3 log files from Stacks v1 that are even remotely similar to v2.

**Comment by ewels** [comment]
Oops, saw this just as I merged. I think keep it all `stacks`, but subfolders by version number are helpful 👍

**Comment by remiolsen** [comment]
No problem. Don't worry, I have no plans on writing a module that support Stacks v1. 😀 

I guess they haven't change the name of `stacks`,  I should at lease be **very** clear in the documentation about version is supported

**Pull request merged**
