### PR TITLE
Added test files for vcftools module.

### PR DESCRIPTION
**Pull request by ehsueh**

### CODE REVIEW

**Comment by ewels** [comment]
Great, thanks! `public_SRP032974.TsTv.qual` is `44M` in size - I take it that not all of this is needed for the MultiQC module? Any chance that you could trim it so that it still works in the same way (and it's clear what it usually looks like) but is not _quite_ as large..?

**Comment by ehsueh** [comment]
I included that one because it seems like MultiQC doesn't like working with big file size.... It's not detecting that file unless I take only a smaller portion of it. :confused:

**Comment by ewels** [comment]
Hi @ehsueh,

The behaviour you're describing is deliberate - anything larger than `config.log_filesize_limit` is ignored by MultiQC by default. This can be changed on a per-user basis, but I'm fairly keen not to change the default as it has a large impact on the run speed of MultiQC. Several tools output summary logs to `stdout` which can be concatenated by users. So MultiQC has to scan through the contents of every file it finds. Including larger files can make the run time very slow.

I've just pulled your code and test data and tried it, and it looks like you do need all of the contents of this file for the plot. As a rule of thumb, I also try to ensure that MultiQC only parses summary statistics rather than calculating anything itself. This is a bit of a special case where you're parsing plot data (essentially already summary statistics), but there's just a massive amount of it. Are these files always this large?

Phil

**Comment by ehsueh** [comment]
Hi @ewels,

Oh I see! 
I don't think all the content of the file is needed for the vcftools TsTv plot since it is basically just a tsv. It is a summary stat with a header line and records with identical format after that first line. So a sub-file including the first header line will run fine (it will just miss the rest of the data points). E.g. `head -n 10000 file > smaller_file` creates a smaller_file that will also be correctly parsed and plot. The problem is it might be too small on the graph (relative to other bigger files) to see (you might have to mouseover the tiny line at the start of the graph to see it).

These type of file doesn't always have to be that big. It really depends on how big and dense is the initial variant vcf file used to generate the vcftools stat files.

Hope that answered your questions. Should I remove that 44M file and do a pull request again?

**Comment by ewels** [comment]
Ok cool - then yes, please make the test file shorter as in your example command. Just save, commit and push, there's no need to close the PR and open a new one - your new commit will automatically be appended here.

Thanks! I'll add more comments on the code PR :)

Phil

**Comment by ehsueh** [comment]
Done! And ok! Thanks for adding more comments on the codes. :smile:

**Comment by ewels** [comment]
Thanks!

**Pull request merged**
