### PR TITLE
Add example csv files for phantompeakqualtools

### PR DESCRIPTION
**Pull request by chuan-wang**

### CODE REVIEW

**Comment by ewels** [comment]
Thanks @chuan-wang! How are these generated?

**Comment by chuan-wang** [comment]
@ewels With the custom R script in the nextflow pipeline.

**Comment by chuan-wang** [comment]
OK, sorry I missed that comments. I will look into it next week. Do you
have any example module in which there is custom R scripts associated?

**Comment by ewels** [comment]
Ah of course, RData files are easy to load in R and difficult in Python. Looks like there is a package to do this: https://stackoverflow.com/a/21288178/713980

But may be overkill. It's probably better to just make the R script generate custom_content files for MultiQC then.

Let's talk about this next week.

**Comment by chuan-wang** [comment]
I have edited the code so that a header line is added in the csv file.

**Comment by ewels** [comment]
Thanks @chuan-wang! I merged just the deepTools commits and removed the phantompeakqualtools commits, now that we're no longer writing a MultiQC module for those.

**Pull request closed without merging**
