### PR TITLE
Add in iVar variants data

### PR DESCRIPTION
**Pull request by apeltzer**
As on the tin 👍  Data provided by @drpatelh

### CODE REVIEW

**Comment by drpatelh** [comment]
```
# iVar variants file

```bash
samtools mpileup \
    -A \
    -d 6000000 \
    -B \
    -Q 0 \
    SAMPLE1_PE.trim.sorted.bam \
    | ivar variants -p SAMPLE1_PE -r GCF_009858895.2_ASM985889v3_genomic.200409.fna -g GCF_009858895.2_ASM985889v3_genomic.200409.gff
```

### Test files added

`SAMPLE1_PE.tsv` (iVar v1.2.2)
```

**Comment by drpatelh** [comment]
Was just prepping the same PR 😅 Could add this to the `README.md` too @apeltzer 👍

**Comment by drpatelh** [comment]
This one should be quite straight forward i.e. take the 4th column from the file and do something like this:
https://github.com/drpatelh/nf-core-viralrecon/blob/397f25529d0ca506666c88d74a5382fcbbbb481e/bin/ivar_variants_to_vcf.py#L68-L73

**Comment by apeltzer** [comment]
Added your stuff too 👍 Yes, it looks much saner than the other one ;-)

**Comment by drpatelh** [comment]
image

FYI: One I generated earlier using custom content.

**Comment by drpatelh** [comment]
Ping @gkarthik! If you do [release soon](https://github.com/andersen-lab/ivar/issues/42#issuecomment-622589820) would be great if you can output simple counts for SNPs/Insertions/Deletions. Can plug this directly into MultiQC without having to parse the variants `tsv` file.

**Comment by ewels** [comment]
Hi @gkarthik - sorry to pester, but do you intend on outputting the summary counts? No problem if not, we can get started on writing this MultiQC module without them. But of course if you do intend on this then we'd rather not make a start on the code.

Thanks!

Phil

**Comment by gkarthik** [comment]
Unfortunately given current ongoing work around SARS-CoV-2 my schedule is very tight. Maybe best to start on the code. I'll keep you informed when I add more information to the logs. Thank you for adding this to MultiQC again!

**Comment by ewels** [comment]
ok, no problem - thanks for letting us know! We'll keep you in the loop 👌

**Pull request merged**
