### PR TITLE
Pangolin: Fix shifted columns in testdata

### PR DESCRIPTION
**Pull request by pontushojer**
Related: https://github.com/cov-lineages/pangolin/issues/531

### CODE REVIEW

**Comment by wm75** [comment]
also: columns were changed with pangolin v4 (just in case you want to support output from very outdated versions of pangolin, too)

**Comment by pontushojer** [comment]
@wm75 Would be great to have some input from an expert on something like this! If you have the time to checkout to test it out and suggest any changes very helpful.

**Comment by ewels** [comment]
Ah nice, thanks! So this was always broken, just that no-one noticed until now?

This test data is from v4, no? `data/modules/pangolin/v4.0/pangolin_4-0.csv`

**Comment by pontushojer** [comment]
Yes, strange indeed that this was overlooked for so long! It must also have been present in the pangolin docs since v4.0 with no one noticing 👀 Suppose these things are easily missed, or perhaps not too many people have looked at it until now.

**Review by ewels — APPROVED** [review]
Well done for spotting! 🦅 👀

**Pull request merged**
