### PR TITLE
example BA csv file

### PR DESCRIPTION
**Pull request by avilella**
Please feel free to move into an aptly named folder of your choice.

### CODE REVIEW

**Comment by ewels** [comment]
Thanks @avilella. I've looked at this file but I'm not sure how useful it is, as the axis is Time rather than calibrated base pairs.. Is the data for base pairs in a file anywhere?

Folder name `bioanalyzer` should be fine I think.

**Comment by avilella** [comment]
see two extra files now.

**Comment by ewels** [comment]
Ok nice, thanks! How did you get these files? A couple of others have put example files into a subfolder with its own `README.md` file in there too just quickly describing how they were generated. Could be nice here too as presumably it's not a standardised command line thing?

**Comment by ewels** [comment]
Thanks again @avilella - I've moved into a `bioanalyzer` directory as suggested. It would still be great if you could add a `README.md` file in there 👍 

Phil

**Pull request merged**
