### PR TITLE
Add test data for ccs

### PR DESCRIPTION
**Pull request by Redmar-van-den-Berg**

### CODE REVIEW

**Comment by ewels** [comment]
Hesitating on this PR because of the new unit test code. MultiQC is a bit shaky on unit testing (as in, there isn't really any) but people have tried to add some in the past in the main repo. I want to have a bit of think about how I want it to be done before accidentally setting a precedent here if that's ok 😅 Will hopefully have time to sit down with MultiQC code soon(ish - there's a bit of a backlog).

Phil

**Comment by Redmar-van-den-Berg** [comment]
Hi,

That makes sense, I didn't notice until I was done developing the new features I needed that the project was using unittest instead of pytest. Since pytest also runs the unittest code that is already in the project, I decided to keep the tests I had already written in. As a last resort, I can always remove the tests that I wrote for CCS, and only keep the example files. That way, we can at least test that the example files do not crash MultiQC.

Slightly offtopic, if you are more interested in having high level tests for MultiQC, you could have a look at [pytest-workflow](https://pytest-workflow.readthedocs.io/en/stable/#writing-tests-with-pytest-workflow). It is quite simple and powerful, in the below example I test to make sure that the statistics I am interested in for my pipeline end up in the MultiQC HTML report.

```yaml
- name: test-workflow-hsmetric-baits
  tags:
    - integration
  command: >
    cromwell run
    --inputs tests/data/config/variant_calling_hsmetric_baits.json
    PacBio-variantcalling.wdl
  files:
    - path: test-output/multiqc/multiqc_report.html
      contains:
        - "Alignment Summary"
        - "GC Coverage Bias"
        - "HSMetrics"
        - "Target Region Coverage"
    - path: test-output/multiqc/multiqc_data.zip
```

**Comment by ewels** [comment]
> The project was using unittest instead of pytest.

The project isn't really using anything at the moment - I guess the code coverage is under 1%. What is there currently was a stab at starting something from a contributor at a hackathon several years ago. It's not more than a stub.

pytest-workflow looks really interesting! Potentially for MultiQC, but especially for @nf-core where we are starting to play with / write something that looks pretty similar for workflows. Thanks for the tip!

**Comment by ewels** [comment]
x-ref https://github.com/ewels/MultiQC/pull/1288

**Comment by ewels** [comment]
ok I figure I've left this long enough and as I think the CI will ignore it there should be no harm in merging it 😄  Can worry about the big picture later..

Thanks again!

**Pull request merged**
