### PR TITLE
Add bcbio metrics generated by bcbio code only.

### PR DESCRIPTION
**Pull request by lpantano**
Hi,

as discussed today (https://github.com/ewels/MultiQC/issues/180#issuecomment-211450096). I am preparing the code for QC metrics that bcbio generates with internal code. 

I will do whatever you recommend. There are no specific tools to generate these metrics, is a combination of BAM stats and python code to show coverage information. Right now we have the report in a Rmd file, but we want to migrate to multiqc. 

Do you think I need to do this as plugin? I can do that, I think we will need to tweak the installation of the plugin according to the documentation you have. I just want to do whatever feels right to you. Bcbio is used by many people as you know, so the line between custom QC metrics, and standard QC metrics is blur to me in this case. 

I am thinking of people who wants to recreate the report only using these QC bcbio metrics files for instance, because bcbio already will provide with a multiqc output, but using all tools.

let me know what you think.

thanks

### CODE REVIEW

**Comment by ewels** [comment]
I think both options are good. If you do it as a plugin and put this on PyPI / Bioconda then the installation is still very easy:
```
pip install multiqc multiqc-bcbio
```

However, given the discussion of a new module system in https://github.com/ewels/MultiQC/issues/181, it might be more suitable to write a bcbio _module_ with sections for each type of output. I think this is the best of the two solutions in the long term as you only want to parse custom content, not _do_ custom things with it.

What do you think? Are you happy to wait until the above issue is decided and potentially implemented? It's quite a large undertaking so may take a little time.

Phil

**Comment by lpantano** [comment]
I get it. I think since multiqc is moving to a module system, I would do the plugin for now, and then move to whatever you decide to implement to handle all the different QC that can appear. You are creating a new big field here. :)

**Comment by lpantano** [comment]
PS: I need to create this for the next couple of weeks because our users are so excited about all the metrics that they wanted now :)

**Comment by lpantano** [comment]
As a last two question related to this:

1. Is ok if I create this plugin inside multiqc organization and then do the changes needed to be a module when you have figured out the way to introduce more modules? If not I can create a new repository under my username, I just want to avoid duplication, but always I can remove my repository when I put the module version in yours.
2. For now, do I have to update the multiqc file to add the new patters for the new files I will need here, right? or there is a way to add this into the plugin code and multiqc will update the pattern to look for?

thanks for all this, as always!

**Comment by ewels** [comment]
1. Yes, though if you want to create it on your own account and fork it into the organisation at a later date that would also be fine. The two are fairly equivalent.
2. The search patterns are loaded into the config, so you can add to this in your module / plugin. _eg:_

```python
from multiqc import config

config.sp['yourtool']['fn'] = '*.mypattern.txt'
```
_(untested)_

When the new system is in place this info will also be in the core `search_patterns.yaml` file. I need to figure out a way to handle this though, so that non-core modules work. Maybe just keeping both, but in such a way that they can be overwritten by user configs.

**Comment by lpantano** [comment]
I am just amazed. It works perfectly. How could you have planned that well! Super easy to add modules in any way! congrats! hope to meet you in person some day just to thanks you how easy will be our life from now on with the report.

**Comment by ewels** [comment]
Great! Glad you like it :)

**Pull request merged**
