### PR TITLE
replaced obsolete qc3C json files

### PR DESCRIPTION
**Pull request by cerebis**
Old test data was accidentally used in the first instance, and I failed to push the corrected files to Github MultiQC_TestData prior to the PR.

### CODE REVIEW

**Comment by ewels** [comment]
Thanks @cerebis! Is it worth keeping both versions of the log files? Where possible I like MultiQC modules to fail gracefully with older versions of logs instead of generating a hard crash.

Phil

**Comment by cerebis** [comment]
I suppose that's a good point. What would be the MultiQC approach to
graceful? Should I simply catch the keyerror and emit a log entry?

**Comment by ewels** [comment]
Yes - if the differences are not huge then I often use `.get()` to access dict keys only if they exist, or just catch KeyErrors as you say. If the differences are huge then in some cases modules actively try to detect old versions and bail with a warning (but I don't think that this is the case here).

If the parsing problem is enough to render the entire log file unusable then it's probably worth a log message. Otherwise if it's just a missing metric or plot then I usually just skip silently, or with a `debug` level log message. If the documentation says that it only supports tool version x onwards then I think that's sufficient.

Phil

**Comment by ewels** [comment]
Thanks for handling this! If you could update this PR to move the log files into subfolders named after the tool versions that would be great. Then we have both outputs to check that it works gracefully and it's super clear what the different files are.

You can probably remove all but one or two of the logs from the older version.

**Pull request merged**
